REM "C:\Program Files (x86)\AVEVA\Everything3D3.1\mon.exe" PROD XXX init "C:\Program Files (x86)\AVEVA\Everything3D3.1\launch.init" TTY -project=RYA -user=COMPANY -pass=CPYRYA -mdb=/RUYA-ALL-PLATFORMS-DESI-DE -macro=\\als.local\NOC\Data\Appli\DigitalAsset\MP\RUYA_data\Batch\Engineering\NOC-RYA-Engineering.MAC
"C:\Program Files\AVEVA\Engineering15.7.1\mon.exe" PROD Engineering init "C:\Program Files\AVEVA\Engineering15.7.1\engineering.init" TTY RYA COMPANY/CPYRYA /ADMIN_BH_DE  $m \\als.local\NOC\Data\Appli\DigitalAsset\MP\RUYA_data\Batch\Engineering\AENG_Export_All_properties.mac
"C:\Program Files\AVEVA\Engineering15.7.1\mon.exe" PROD Engineering init "C:\Program Files\AVEVA\Engineering15.7.1\engineering.init" TTY RYA COMPANY/CPYRYA /ADMIN_CPP_(BJ^&BK)_DE $m \\als.local\NOC\Data\Appli\DigitalAsset\MP\RUYA_data\Batch\Engineering\AENG_Export_All_properties.mac
"C:\Program Files\AVEVA\Engineering15.7.1\mon.exe" PROD Engineering init "C:\Program Files\AVEVA\Engineering15.7.1\engineering.init" TTY RYA COMPANY/CPYRYA /ADMIN_WHP_DE $m \\als.local\NOC\Data\Appli\DigitalAsset\MP\RUYA_data\Batch\Engineering\AENG_Export_All_properties.mac
REM $m \\als.local\NOC\Data\Appli\DigitalAsset\MP\RUYA_data\Batch\Engineering\NOC-RYA-Engineering.repv


REM $m \\als.local\NOC\Data\Appli\DigitalAsset\MP\RUYA_data\Batch\Engineering\NOC-RYA-Engineering.MAC